In [1]:
import numpy  as  np
a = [1,2,3]
b = [4,5,6]
c = np.array((a,b))
print(c)
print(c+c)
print(c*c)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]


In [3]:
print(c.shape)
print(c.dtype)

(2, 3)
int32


In [4]:
np.dot(c,c)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [5]:
np.dot(c.T,c)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])